[package]
name = "taskband"
version = "0.1.4"
edition = "2021"
description = "Highly customizable Windows taskbar with custom plugins"
license = "MIT"
repository = "https://github.com/mnismi/taskband"
readme = "README.md"
keywords = ["taskbar", "windows", "waybar", "statusbar"]
categories = ["gui"]

[[bin]]
name = "Taskband"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
json5 = "1"
serde_json = "1"
tiny_http = "0.12"
getrandom = "0.2"

[build-dependencies]
winresource = "0.1"

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Devices_Display",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_Registry",
]
